#!/bin/bash

echo -e "LinkedList.cpp " $(python3 lexer.py Cpp/LinkedList.hpp)
echo -e "LinkedList.elm " $(python3 lexer.py Elm/src/LinkedList.elm)
echo -e "LinkedList.hs " $(python3 lexer.py Haskell/LinkedList.hs)
echo -e "LinkedList.ts " $(python3 lexer.py TypeScript/LinkedList.ts)

echo ""
echo -e "BST.cpp " $(python3 lexer.py Cpp/BinarySearchTree.hpp)
echo -e "BST.elm " $(python3 lexer.py Elm/src/BinarySearchTree.elm)
echo -e "BST.hs " $(python3 lexer.py Haskell/BinarySearchTree.hs)
echo -e "BST.ts " $(python3 lexer.py TypeScript/BinarySearchTree.ts)