name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      # - uses: justgook/setup-elm@1.2.0
      - uses: actions/setup-haskell@v1.1.3
      - run: ruby -v
      - run: g++ -v
      - run: node --version
      - run: tsc --version
      - run: ghc --version
      # - run: elm --version
      - name: Run tests
        run: ruby tests.rb
