name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - uses: jorelali/setup-elm@v2
        with:
          elm-version: 0.19.1
      - uses: actions/setup-haskell@v1.1.3
        with:
          stack-no-global: true
          enable-stack: true
      - name: Run tests
        run: ./tests
